name: Grade Submissions

on:
  push:
    paths: 
      - 'stage1/**'

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Make script executable
        run: chmod +x grade.sh
      
      - name: Run grading script
        run: ./grade.sh stage1

      - name: Proceed to next stage
        if: success()
        run: |
          curl -X POST https://unfurbished-nonmanifest-alishia.ngrok-free.dev/ \
          --connect-timeout 20 \
          --max-time 60 \
          -H "Content-Type: application/json" \
          -d '{
            "team_name": "${{ github.repository }}",
            "stage": 2
          }'
